---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: chbot241
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: chbot241 
  name: chbot241
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi