apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: chbot241
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: chbot241 
  name: chbot241
spec:
  ports:
  - port: 8501
    protocol: TCP
    targetPort: 8501
  selector:
    app.kubernetes.io/instance: chbot241 
